<a href="https://colab.research.google.com/github/KandiJayana/Advanced-Data-Modeling/blob/main/7_Indexacao_e_Slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Manipulacao de Dados com Numpy

#### Indexacao e Slicing

In [1]:
# Vamos começar do inicio que basicamente e voce importar o pacote numpy
# O Anaconda Python ja possui o NumPy instalado por isso nao precisa instalar
# Caso voce não consiga importa-lo tente usar o comando !pip install numpy e depois faça a importacao
import numpy as np

# Veja que importamos o numpy e demos o "apelido" de np que sempre sera utilizado quando formos chamar as funcoes do numpy

In [2]:
# Vamos verificar a versao utilizada neste curso do numpy, e importante que voce utilize a mesma versao
print(np.__version__)

1.26.4


### Indexacao e Slicing com Numpy

In [3]:
# Vamos criar um array simples como voce conhece ja
array1 = np.array([1, 2, 3, 4, 5])
array1

array([1, 2, 3, 4, 5])

In [4]:
# Vamos buscar o primeiro elemento do array
array1[0]

1

In [5]:
# Vamos buscar o segundo elemento do array
array1[1]

2

In [6]:
# Vamos buscar o ultimo elemento do array
# Veja que e como se tivessemos indo de traz para frente
array1[-1]

5

In [7]:
# Vamos criar um array com arange
array2 = np.arange(11); array2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
# Invertendo o Array
# array[início : fim : passo]
#array2[:: -1]
#array2[2 : 9 : 2]
array2[9 : 2 : -2]

array([9, 7, 5, 3])

In [9]:
# Invertendo o array
# So que agora queremos os elementos de 2 em 2
array2[::-2]

array([10,  8,  6,  4,  2,  0])

# Exercícios

### Exercício 1: Salvando Arrays

Crie um array e salve-o em .npy. Carregue o array salvo.

<!--
# Criação do array
array = np.array([1, 2, 3, 4, 5])

# Salvando o array
np.save("meu_array.npy", array)

# Carregando o array salvo
array_carregado = np.load("meu_array.npy")
print(array_carregado)
-->

In [19]:
# R:

# Criação do array
meu_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Salvando o array
np.save("meu_array.npy", meu_array)

# Carregando o array salvo
array_carregado = np.load("meu_array.npy")
print(array_carregado)

[ 1  2  3  4  5  6  7  8  9 10]


### Exercício 2: Extraindo Subarrays com Slicing

Dado o array bidimensional abaixo, extraia:

array = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

- A primeira linha.
- As duas últimas colunas.
- A submatriz formada pelas duas primeiras linhas e as três primeiras colunas.

<!--
# Primeira linha
primeira_linha = array[0, :]
print("Primeira linha:", primeira_linha)

# Duas últimas colunas
duas_ultimas_colunas = array[:, -2:]
print("Duas últimas colunas:\n", duas_ultimas_colunas)

# Submatriz 2x3 das duas primeiras linhas e três primeiras colunas
submatriz_2x3 = array[:2, :3]
print("Submatriz 2x3:\n", submatriz_2x3)
-->

In [27]:
# R:

# Dado o array bidimensional abaixo, extraia:
#                  0  1  2  3
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])
#                 -4, -3, -2, -1


In [28]:
#- A primeira linha.
#- As duas últimas colunas.
#- A submatriz formada pelas duas primeiras linhas e as três primeiras colunas.


# Primeira linha
primeira_linha = array[0, :]
print("Primeira linha:", primeira_linha)



Primeira linha: [1 2 3 4]


In [29]:
# Duas últimas colunas
duas_ultimas_colunas = array[:, -2:]
print("Duas últimas colunas:\n", duas_ultimas_colunas)



Duas últimas colunas:
 [[ 3  4]
 [ 7  8]
 [11 12]]


In [31]:
# Submatriz 2x3 das duas primeiras linhas e três primeiras colunas
submatriz_2x3 = array[:2, :]
print("Submatriz 2x3:\n", submatriz_2x3)

Submatriz 2x3:
 [[1 2 3 4]
 [5 6 7 8]]
