<a href="https://colab.research.google.com/github/KandiJayana/Advanced-Data-Modeling/blob/main/9_Array_Multidimensional.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Numpy

#### Array Multidimensional!

In [1]:
# Vamos começar do inicio que basicamente e voce importar o pacote numpy
# O Anaconda Python ja possui o NumPy instalado por isso nao precisa instalar
# Caso voce não consiga importa-lo tente usar o comando !pip install numpy e depois faça a importacao
import numpy as np

# Veja que importamos o numpy e demos o "apelido" de np que sempre sera utilizado quando formos chamar as funcoes do numpy

In [2]:
# Vamos verificar a versao utilizada neste curso do numpy, e importante que voce utilize a mesma versao
print(np.__version__)

1.26.4


In [3]:
# criar um array com shape 3,3
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]]);array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
# retorna os elementos da terceira linha da matriz
# o resultado é exatamente a ultima linha do
# A linha de indice 2

array1[2]

array([7, 8, 9])

In [5]:
# retorna os elementos da terceira linha da matriz de outra forma
# o resultado é exatamente a ultima linha do
# A linha de indice 2

array1[2,]

array([7, 8, 9])

In [6]:
# Retornando todas as linhas da segunda coluna da matriz
# queremos todas as linhas, e apenas a coluna de indice 1
# selecionamos uma coluna porem retorna uma unica lista de valores

array1[:,1]

array([2, 5, 8])

In [7]:
# Fatiamento/Slicing da matriz
# queremos retornar a linha de indice 2 e
# a coluna de indice 1

array1[2,1]

8

In [8]:
# usando atribuicao
# alterar um dos elementos da matriz
# alterar o elemento da linha de indice 1 e coluna indice 2

# chamamos o array e
# indicamos atravez do slicing o elemento que queremos atribuir o novo valor
# após, o elemento foi alterado

array1[1,2] = 16 ; array1

array([[ 1,  2,  3],
       [ 4,  5, 16],
       [ 7,  8,  9]])

In [11]:
# criando mais um array para fazer um teste
# Temos um array de 3 elementos

array2 = np.array([10,11,12])
array2.shape

(3,)

In [10]:
# ao chamar um elemento que nao existe no array
# Retorna um erro
array2[6]

IndexError: index 6 is out of bounds for axis 0 with size 3

# Exercícios

### Exercício 1. Calcule o produto de dois arrays de matriz 2x2.

<!--
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
produto_ponto = np.dot(arr1, arr2)
print(produto_ponto)
-->

In [12]:
# R:

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
produto_ponto = np.dot(arr1, arr2)
print(produto_ponto)

[[19 22]
 [43 50]]
